## if you want to run this on cloud run.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: qlyx
spec:
  template:
    spec:
      containers:
        - image: gcr.io/<your-project>/qlyx:1.0.2
          env: # should be secret... TODO
            - name: DATABASE_URL
              value: "DB-URL"
            - name: DATABASE_PASSWORD
              value: "<ENTER-PWD>"
            - name: PROTECT_LEADERBOARD
              value: 1
            - name: LOCATION_CONFIG # base64 encoded utf8 string to allow for emojis
              value: "W3sibG9jYXRpb24iOiJERSIsICJsYWJlbCI6ICLwn4ep8J+HqiBIYW1idXJnIn1d" # echo -'[{"location":"DE", "label": "🇩🇪 Hamburg"}]' | base64
            - name: ADM_PWD
              value: "<SomePwdToProtectTheBackend>"
          ports:
            - containerPort: 3000